### ISSUE TITLE
Adafruit Feather 32u4 Bluefruit LE HID Gamepad Support

### ISSUE THREAD

**Issue by ddragon1999** [adafruit/Adafruit-Feather-32u4-Basic-Proto-PCB#1]
Does anybody know if there is an HID Gamepad library for the Adafruit Feather 32u4 Bluefruit LE. I am trying to make a game pad Bluetooth and I do not want it to be recognized as a HID Keyboard by Windows or Android devices. The thing I do not understand is that there is an AT command to activate the HID Gamepad "AT+BLEHIDGAMEPADEN" but it does not seem like HID Gamepad support is not in the Adafruit library or there are no examples for and HID Gamepad. I would greatly appreciate it if anybody could give me some info about this.

**Comment by ladyada** [comment]
hi please post in the forums, this is not where we do tech support

**Comment by bergstar** [comment]
@ladyada with all do respect, this is not a tech support question.
Posted on forums as well, https://forums.adafruit.com/viewtopic.php?f=57&t=169085
